name: CICD

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    
    - name: Cache gradle
      id: cache
      uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build JAR
      run: gradle build

    - name: Create Release
      if: github.ref == 'refs/heads/master'
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.GITHUB_REF_SLUG }}-${{ github.run_number }}
        release_name: ${{ env.GITHUB_REF_SLUG }}-${{ github.run_number }}
        draft: ${{ github.ref == 'refs/heads/dev' }}
        prerelease: ${{ github.ref != 'refs/heads/release' }}

    - name: Upload plugin
      if: github.ref == 'refs/heads/master'
      id: upload-plugin
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: plugin/build/libs/altv-kotlin.jar
        asset_name: altv-kotlin.jar
        asset_content_type: application/zip
