name: CICD

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: FranzDiebold/github-env-vars-action@v1.2.1
    - uses: actions/checkout@v1

    - name: Cache gradle
      id: cache
      uses: actions/cache@v2.1.3
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Set up JDK 11
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 11
        server-id: github
        settings-path: ${{ github.workspace }}

    - name: Build JAR
      run: gradle build

    - name: Create Release
      if: github.ref == 'refs/heads/master'
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.GITHUB_REF_NAME_SLUG }}-${{ github.run_number }}
        release_name: ${{ env.GITHUB_REF_NAME_SLUG }}-${{ github.run_number }}
        draft: false
        prerelease: false

    - name: Upload plugin
      if: github.ref == 'refs/heads/master'
      id: upload-plugin
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: plugin/build/libs/altv-kotlin.jar
        asset_name: altv-kotlin.jar
        asset_content_type: application/zip
